name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.0

environment:
  sdk: '>=3.2.0'

dependencies:
  archive: ^3.4.9 
  quiver: ^3.2.1
  xml: ^6.4.2
  collection: ^1.18.0 
  path: ^1.8.3

dev_dependencies:
  test: ^1.16.7
  lints: ^3.0.0