name: epubx
description: Epub Parser for Dart. Epub package fork. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/rbcprolabs/epubx.dart
issue_tracker: https://github.com/rbcprolabs/epubx.dart
version: 4.0.0

environment:
  sdk: '>=3.5.0'

dependencies:
  archive: ^4.0.2 
  quiver: ^3.2.2
  xml: ^6.5.0
  collection: ^1.19.1 
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.14
  lints: ^5.1.1
